notes/urls.py
from django.conf.urls import url
from . import views

app_name = 'notes'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^create/$', views.create, name='create'),
	url(r'^list/$', views.notes, name='list'),
]

travis/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from notes import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^notes/', include('notes.urls')),
]

notes/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.
class Notebook(models.Model):
	"""docstring for Notebook"""
	title = models.CharField( max_length = 200, default = "Untitled Notebook" )
	owner = models.ForeignKey( 'auth.User' )
	created_at = models.DateTimeField( 'date created', default=timezone.now )
	updated_at = models.DateTimeField( 'date updated', default=timezone.now )

	def __str__(self):
		return self.title

class Note(models.Model):

	title = models.CharField( max_length = 200, default = "Untitled Note" )
	notebook = models.ForeignKey( Notebook, on_delete = models.CASCADE )
	body = models.TextField( blank=True, null=True )

	def __str__(self):
		return self.title
		

notes/views.py
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse

from .models import Notebook,Note
# Create your views here.
def index(request):
	notebooks = Notebook.objects.all()
	return render(request, 'notes/index.html',  { 'notebooks' : notebooks })

def create(request):
	note = Note(title=request.POST['title'],body=request.POST['body'],notebook_id=1)
	note.save()

	return HttpResponseRedirect(reverse('notes:index'))

def notes(request):
	return render(request, 'notes/list_notes.html', {})

notes/templates/notes/index.html
{% extends 'notes/master.html' %}

{% block content %}

<!-- <h3>Travis says Hello! Welcome to my world!</h3> -->
<!-- <ul>
	{% for notebook in notebooks %}
	<li>
		{{ notebook.title }} <br>
		0-0-0-0-0-0-0-0-0-0-0 <br>
		{% for note in notebook.note_set.all %}
		{{ note.title }}
		{% endfor %}
	</li>
	{% endfor %}
</ul> -->
<div class="row">
	<div class="col">
		<form action="{% url 'notes:create' %}" method="post" id="createNotesForm">
			<h3>Compose an Epic Today</h3>
			<hr>
			{% csrf_token %}
			<div class="form-group">
				<input type="text" class="form-control" name="title" placeholder="All Stories Begins with a Title">
			</div>
			<div class="form-group">
				<input type="hidden" id="noteContentBody" name="body">
			</div>
			<div class="form-group">
				
				<div id="toolbarContainer">

					<div class="ql-formats">
						<select class="ql-size">
						   <!-- Note a missing, thus falsy value, is used to reset to default -->
						   <option selected></option>
						   <option value="large"></option>
						   <option value="huge"></option>
						</select>

						<select class="ql-font">
						    <option value="lato" selected="selected">Lato</option>
						    <option value="robotoslab">Roboto Slab</option>
						</select>
					</div>

					<div class="ql-formats">
						<!-- Add a bold button -->
						<button class="ql-bold"></button>
						<button class="ql-italic"></button>
						<button class="ql-strike"></button>
					</div>

					<div class="ql-formats">
						<button class="ql-script" value="sub"></button>
						<button class="ql-script" value="super"></button>
					</div>
					
					<div class="ql-formats">
					 <button class="ql-image" value="image"></button>
					 <button class="ql-link" value="link"></button>
					</div>
				</div>
				
				<div id="notesEditor"></div>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-primary">Create Note</button>
			</div>
		</form>
	</div>
</div>

{% endblock %}

notes/templates/notes/list_notes.html
{% extends 'notes/master.html' %}

{% block content %}

	<h3>Let's show something amazing here!</h3>

{% endblock %} 

notes/templates/notes/master.html
{% load static %}
<html>
<head>
	<meta charset="UTF-8">
	<title>Travis | A Web-based Note-maker</title>
	
	<!-- font imports -->
	<link href="https://fonts.googleapis.com/css?family=Lato|Roboto+Slab" rel="stylesheet">
	
	<link rel="stylesheet" href="{% static 'notes/css/style.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/css/bootstrap.css" integrity="sha256-fDZ6wHbmob72H9d6oq3P6/F3Hc+wHBjdi6FTsUvvQjs=" crossorigin="anonymous" />
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/quill/1.2.3/quill.snow.css" integrity="sha256-EQa7kTy5k5Uenc6l0el6y4gEHWNILk9A4T8jPCFGEJE=" crossorigin="anonymous" />
</head>
<body>
	
	<div class="container-fluid">
		
		{% include 'notes/navbar.html' %}

		{% block content %}
		{% endblock %}
	</div>

	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/quill/1.2.3/quill.js" integrity="sha256-xByhgqg4UDz1dj5ytp1sAjtm8gylWGu2y3qeRD/rRfc=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

	<script src="{% static 'notes/js/app.js' %}"></script>
</body>
</html>

notes/templates/notes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Travis</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Notebooks</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Notes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Administration</a>
      </li>
      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown link
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li> -->
    </ul>
  </div>
</nav>